# Generated by Django 4.0.5 on 2022-07-22 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longlink', models.CharField(max_length=500, verbose_name='Длинная ссылка')),
                ('slug', models.SlugField(unique=True, verbose_name='Короткая ссылка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Cсылка',
                'verbose_name_plural': 'Cсылки',
            },
        ),
    ]
