# Generated by Django 4.0.5 on 2022-09-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_alter_link_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(default=1, max_length=500, verbose_name='Длинная ссылка'),
            preserve_default=False,
        ),
    ]
