# Generated by Django 4.1 on 2022-09-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_link_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='longlink',
            field=models.CharField(max_length=1000, verbose_name='Длинная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок ссылки'),
        ),
    ]
