# Generated by Django 4.0.5 on 2022-07-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_agreement_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='user.png', upload_to='user_images', verbose_name='Фото пользователя'),
        ),
    ]
