# Generated by Django 4.0.5 on 2022-07-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_gender_remove_profile_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
