# Generated by Django 4.0.5 on 2022-09-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='user.webp', upload_to='user_images', verbose_name='Фото пользователя'),
        ),
    ]
